#!/usr/bin/env python3
"""
notify_publish.py — Send a post-publish email summary via Gmail SMTP.

Why Gmail SMTP, not Formspree:
  Formspree free tier rejects server-side POSTs with reCAPTCHA enabled
  (returns 403 with "set a custom key or reCAPTCHA must be disabled").
  Gmail SMTP via an App Password is unmetered, bulletproof, and runs
  entirely between your account and itself.

One-time setup (3 minutes):
  1. Visit https://myaccount.google.com/apppasswords (requires 2FA on Gmail)
  2. Create an App Password — name it "cbtcbook publish"
  3. Append this line to /Users/chunjun/CBTC_book_site/.env:
        GMAIL_APP_PASSWORD=xxxx xxxx xxxx xxxx
     (the 16-char password Google shows you, with or without spaces)

Reads:
  publish-queue.yml      — to compute remaining count + next batch
  site-src/src/content/blog/*.md  — to count what's already shipped

Args:
  --slugs  comma-separated list of slugs published in this run
  --date   ISO date of this publish (defaults to today)
  --dry    print the email instead of sending
"""
from __future__ import annotations
import argparse
import datetime as dt
import os
import re
import smtplib
import sys
from email.mime.text import MIMEText
from email.utils import formatdate
from pathlib import Path

THIS = Path(__file__).resolve()
sys.path.insert(0, str(THIS.parent))
from openai_helper import load_env  # noqa: E402

ROOT = THIS.parent.parent
QUEUE = ROOT / "publish-queue.yml"
CONTENT = ROOT / "site-src" / "src" / "content" / "blog"

GMAIL_USER = "franciscowang2008@gmail.com"
GMAIL_HOST = "smtp.gmail.com"
GMAIL_PORT = 465  # SMTPS (implicit TLS)


def parse_queue_slugs() -> list[tuple[str, list[str]]]:
    out: list[tuple[str, list[str]]] = []
    cur_date: str | None = None
    cur_slugs: list[str] = []
    for line in QUEUE.read_text().splitlines():
        m = re.match(r'^"(\d{4}-\d{2}-\d{2})":', line)
        if m:
            if cur_date and cur_slugs:
                out.append((cur_date, cur_slugs))
            cur_date = m.group(1)
            cur_slugs = []
            continue
        m2 = re.match(r"^\s*-\s+([a-z0-9-]+)\s*$", line)
        if m2 and cur_date:
            cur_slugs.append(m2.group(1))
    if cur_date and cur_slugs:
        out.append((cur_date, cur_slugs))
    return out


def published_slugs() -> set[str]:
    if not CONTENT.exists():
        return set()
    return {p.stem for p in CONTENT.glob("*.md")}


def build_message(today_date: str, today_slugs: list[str]) -> tuple[str, str]:
    queue = parse_queue_slugs()
    live = published_slugs()
    total_published = len(live)
    remaining_dates = [(d, s) for d, s in queue if d > today_date]
    remaining_count = sum(len(s) for _, s in remaining_dates)
    next_date = remaining_dates[0][0] if remaining_dates else None
    next_slugs = remaining_dates[0][1] if remaining_dates else []
    end_date = remaining_dates[-1][0] if remaining_dates else today_date

    n = len(today_slugs)
    subject = (f"cbtcbook publish — {today_date} — "
               f"{n} article{'s' if n != 1 else ''}")

    lines: list[str] = []
    lines.append(f"Today's publish ({today_date}):")
    if today_slugs:
        for s in today_slugs:
            lines.append(f"  ✓ {s}")
            lines.append(f"    https://cbtcbook.com/blog/{s}/")
    else:
        lines.append("  (no articles scheduled — script ran as no-op)")

    lines.append("")
    lines.append("Stats:")
    lines.append(f"  Published today:    {n}")
    lines.append(f"  Total live on site: {total_published}")
    lines.append(f"  Remaining in queue: {remaining_count}")
    lines.append(f"  Schedule completes: {end_date}")

    if next_date:
        lines.append("")
        lines.append(f"Next batch — {next_date} "
                     f"({len(next_slugs)} article{'s' if len(next_slugs) != 1 else ''}):")
        for s in next_slugs:
            lines.append(f"  · {s}")

    lines.append("")
    lines.append("—")
    lines.append("Auto-generated by the daily-publish GitHub Actions workflow.")
    lines.append("Manage schedule: edit publish-queue.yml and push.")
    lines.append("Pause publishing: gh workflow disable \"Daily blog publish\" "
                 "--repo fracicsowang/cbtc-book-site")

    return subject, "\n".join(lines)


def send_via_gmail(subject: str, body: str) -> bool:
    load_env()
    pw = os.environ.get("GMAIL_APP_PASSWORD")
    if not pw:
        print("ERROR: GMAIL_APP_PASSWORD not set in .env\n"
              "Get one at https://myaccount.google.com/apppasswords\n"
              "Then add to /Users/chunjun/CBTC_book_site/.env:\n"
              "  GMAIL_APP_PASSWORD=xxxx xxxx xxxx xxxx",
              file=sys.stderr)
        return False
    pw = pw.replace(" ", "")  # tolerate spaces in the App Password

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = GMAIL_USER
    msg["Date"] = formatdate(localtime=True)

    try:
        with smtplib.SMTP_SSL(GMAIL_HOST, GMAIL_PORT, timeout=20) as smtp:
            smtp.login(GMAIL_USER, pw)
            smtp.sendmail(GMAIL_USER, [GMAIL_USER], msg.as_string())
        return True
    except Exception as ex:
        print(f"ERROR: Gmail SMTP send failed: {ex}", file=sys.stderr)
        return False


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--slugs", default="", help="comma-separated slugs published")
    ap.add_argument("--date", default=dt.date.today().isoformat())
    ap.add_argument("--dry", action="store_true",
                    help="print the email instead of sending")
    args = ap.parse_args()

    today_slugs = [s.strip() for s in args.slugs.split(",") if s.strip()]
    subject, body = build_message(args.date, today_slugs)

    if args.dry:
        print(f"To: {GMAIL_USER}")
        print(f"Subject: {subject}\n")
        print(body)
        return 0

    ok = send_via_gmail(subject, body)
    print(f"notify: {'sent ✓' if ok else 'FAILED ✗'} → {subject}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
